setwd("//wsl.localhost/Ubuntu/home/zxy0303/project/scRNA")
library(Seurat)
counts_matrix1 <- read.table("scc13.txt", header = TRUE, sep = "\t")
seurat_obj1 <- CreateSeuratObject(counts = counts_matrix1)
counts_matrix2 <- read.table("cal27.txt", header = TRUE, sep = "\t")
seurat_obj2 <- CreateSeuratObject(counts = counts_matrix2)
seurat_obj1[["percent.mito"]] <- PercentageFeatureSet(seurat_obj1, pattern = "^hg19-MT-")
seurat_obj2[["percent.mito"]] <- PercentageFeatureSet(seurat_obj2, pattern = "^hg19-MT-")
seurat_obj1 <- subset(seurat_obj1, subset = nFeature_RNA > 200 & percent.mito < 10)
seurat_obj2 <- subset(seurat_obj2, subset = nFeature_RNA > 200 & percent.mito < 10)
merged_seurat_obj <- merge(seurat_obj1, y = c(seurat_obj2), add.cell.ids = c("scc13", "cal27"))